### PR TITLE
merge: darqnet web app version

### PR DESCRIPTION
**Pull request by contreau**

### CODE REVIEW

**Review by oed — COMMENTED** [review]
Looks good, but would you mind creating a `backup` folder that contains `ceremony.js`, the old `seedsplit.js` and the `sermons` folder?

**Comment by contreau** [comment]
Yep, backup folder is now included on the latest commit.

**Review by oed — APPROVED** [review]
lgtm, thanks!

**Comment by oed** [comment]
There's a conflict on `seedsplit.js` it looks like. Would you mind resolving that so that I can merge?

**Comment by contreau** [comment]
A while back I had to tweak the import formatting slightly on the bip39 dependency in `seedsplit.js` in order for it to work properly in the web app version. You can see the difference in my branch at `src/js/seedsplit.js` Not sure I can see where to resolve it, given that?

**Comment by oed** [comment]
Try merging the master branch into this branch?

**Comment by contreau** [comment]
Do I need write access on the master branch to do that?

**Comment by oed** [comment]
No you should just be able to do something along the lines of:

```
$ git remote add oed https://github.com/oed/darqnet.git
$ git checkout oed/master
$ git pull
$ git checkout zenDev-2/master
$ git merge oed/master
```

**Comment by contreau** [comment]
done, looks like there's no conflict now!

**Review by oed — APPROVED** [review]
Great, thanks!

**Pull request merged**
